'use strict';
const $=id=>document.getElementById(id);
let META={},stores=[],matches=[],limit=30,rate='',towns=[];
const norm=s=>String(s).normalize('NFKC').toLowerCase().replace(/[\s　]+/g,' ').trim();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function campaignAt(date=new Date()) {const n=+date;return (n>=Date.parse('2026-10-01T10:00:00+09:00')&&n<Date.parse('2026-11-01T00:00:00+09:00'))||(n>=Date.parse('2026-12-01T10:00:00+09:00')&&n<Date.parse('2027-02-01T00:00:00+09:00'));}
function campaign(){return $('mode').value==='campaign'||($('mode').value==='auto'&&campaignAt());}
function townOf(address){return address.match(/^([^\d０-９\s（(]+?)(?=[\d０-９\s（(]|$)/)?.[1]||address||'住所未掲載';}
const aliases={'スーパー':['スーパー','スーパーマーケット'],'ドラッグストア':['ドラッグ','薬局'],'コンビニ':['コンビニ'],'カフェ':['カフェ','喫茶'],'本八幡':['本八幡','八幡'],'南行徳':['南行徳','相之川','新井','欠真間'],'行徳':['行徳','湊','香取','押切','本塩','福栄','末広'],'妙典':['妙典','富浜','本塩'],'市川駅':['市川1','市川2','市川3','市川南','新田']};
function wordMatch(s,w){const values=aliases[w]||[w];return values.some(v=>s.searchText.includes(norm(v)));}
function getFiltered(){const words=norm($('query').value).split(' ').filter(Boolean);return stores.filter(s=>(!rate||s.normalRate===Number(rate))&&(!$('town').value||s.town===$('town').value)&&(!$('category').value||s.category===$('category').value)&&(!$('type').value||s.type===$('type').value)&&(!$('cash').checked||s.cash)&&(!$('card').checked||s.card)&&(!$('furusato').checked||s.furusato)&&words.every(w=>wordMatch(s,w)));}
function render(clearFilters=true){if(clearFilters)limit=30;matches=getFiltered();const camp=campaign();$('count').textContent=matches.length.toLocaleString('ja-JP');$('summary').textContent=`${camp?'キャンペーン時':'通常時'}の還元率を表示 · 全${stores.length.toLocaleString('ja-JP')}件 · ${META.updated.slice(5).replace('-','/')}更新`;
 document.querySelectorAll('[data-rate]').forEach(b=>{const v=b.dataset.rate;b.classList.toggle('selected',v===rate);b.setAttribute('aria-pressed',String(v===rate));if(v)b.textContent=(camp?(v==='5'?30:10):v)+'％';});
 $('period').textContent=campaignAt()?'日程上はキャンペーン期間内 · 予算到達で早期終了あり':'現在は予定されたキャンペーン期間外です';
 $('results').innerHTML=matches.slice(0,limit).map(s=>{const r=camp?s.campaignRate:s.normalRate;const pay=(title,v)=>`<p><span>${title}</span><span class="${v?'yes':'unknown'}">${v?'可':'可の記載なし'}</span></p>`;const moving=!s.address||/市内各所|イベント|移動販売/.test(s.address);return `<article class="store"><div class="store-top"><div><span class="type">${esc(s.category)} / ${esc(s.type)}</span><h3>${esc(s.name)}</h3></div><div class="rate ${s.normalRate===1?'ten':''}"><b>${r}</b>％<small>${camp?'期間中':'通常'}</small></div></div><p class="address">${esc(s.address||'住所未掲載')}</p><div class="payments">${pay('現金併用',s.cash)}${pay('ICHICO専用カード',s.card)}${pay('ふるさとポイント',s.furusato)}<p><span>クレジットカード・併用</span><span class="unknown">未確認</span></p></div><div class="links">${moving?'<span class="unknown">出店場所は要確認</span>':`<a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent('千葉県市川市'+s.address+' '+s.name)}" target="_blank" rel="noopener">地図で見る</a>`}<a href="${esc(s.source)}" target="_blank" rel="noopener">公式掲載</a></div></article>`;}).join('')||'<div class="empty"><h3>条件に合うお店が見つかりません</h3><p>キーワードを短くするか、支払い条件や町名の絞り込みを外してください。</p></div>';
 $('more').hidden=limit>=matches.length; $('download').disabled=!matches.length; if(window.onRender)onRender(matches,camp);
}
function clearFiltersForm(){ $('searchForm').reset();rate='';$('interpretation').hidden=true; }
function parseQuestion(){const q=norm($('question').value);if(!q)return;const original=$('question').value;clearFiltersForm();$('question').value=original;
 const notes=[];if(/30\s*%|10\s*%/.test(q)){$('mode').value='campaign';rate=/30\s*%/.test(q)?'5':'1';notes.push(`${rate==='5'?30:10}％（キャンペーン時）`);}else if(/(?:^|[^0-9])5\s*%|(?:^|[^0-9])1\s*%/.test(q)){$('mode').value='normal';rate=/5\s*%/.test(q)?'5':'1';notes.push(`${rate}％（通常時）`);}
 const negative=/不可|できない|使えない|以外|なし|除く/.test(q);
 if(!negative){if(/現金/.test(q)){$('cash').checked=true;notes.push('現金併用可');}if(/カード/.test(q)&&!/クレジット|クレカ/.test(q)){$('card').checked=true;notes.push('ICHICO専用カード可');}if(/ふるさと/.test(q)){$('furusato').checked=true;notes.push('ふるさとポイント可');}}
 const tokens=[];const places=[...new Set(['南行徳','本八幡','市川駅','行徳','妙典',...towns])].sort((a,b)=>b.length-a.length);let rest=q;for(const p of places){if(p.length>=2&&rest.includes(norm(p))){tokens.push(p);rest=rest.replaceAll(norm(p),'');break;}}
 const kinds=['スーパー','ドラッグストア','コンビニ','カフェ','ラーメン','美容','居酒屋','米屋','焼肉','パン','寿司','薬局'];for(const k of kinds){if(rest.includes(k)){tokens.push(k);rest=rest.replaceAll(k,'');}}
 if(/飲食|レストラン/.test(rest)){$('category').value='飲食';notes.push('飲食');}
 $('query').value=tokens.join(' ');notes.push(...tokens);render();$('interpretation').hidden=false;
 const warnings=[];if(negative)warnings.push('「不可」「以外」などの否定条件は読み取れません。');if(/クレジット|クレカ/.test(q))warnings.push('クレジットカード対応・併用は未確認です。');if(/近く|周辺|駅|徒歩|現在地/.test(q))warnings.push('地名の関連文字で検索します。距離・徒歩時間は判定しません。');
 $('interpretation').textContent=`読み取った条件：${notes.join('・')||'なし'}。${warnings.join('')}表示した条件のみを適用しています。店名など読み取れない条件は上のキーワード欄に入力してください。`;
}
function csvText(rows){const headers=['店名','住所','町名','カテゴリ','業種','通常還元率(%)','キャンペーン還元率(%)','現金併用','ICHICO専用カード','ふるさとポイント','クレジットカード・併用','確認日','公式出典'];const yn=v=>v?'可':'可の記載なし';const safe=v=>{let x=String(v??'');if(/^[=+@\-]/.test(x))x="'"+x;return '"'+x.replaceAll('"','""')+'"';};return '\uFEFF'+[headers,...rows.map(s=>[s.name,s.address,s.town,s.category,s.type,s.normalRate,s.campaignRate,yn(s.cash),yn(s.card),yn(s.furusato),'未確認',s.checked,s.source])].map(r=>r.map(safe).join(',')).join('\r\n');}
$('searchForm').addEventListener('submit',e=>{e.preventDefault();$('interpretation').hidden=true;render();});
['town','category','type','mode','cash','card','furusato'].forEach(id=>$(id).addEventListener('change',()=>render()));
$('query').addEventListener('input',()=>{render();$('interpretation').hidden=true;});
document.querySelectorAll('[data-rate]').forEach(b=>b.addEventListener('click',()=>{rate=b.dataset.rate;render();}));
$('clearFilters').addEventListener('click',()=>{clearFiltersForm();render();});$('ask').addEventListener('click',parseQuestion);$('more').addEventListener('click',()=>{limit+=30;render(false);});
$('download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([csvText(matches)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='ICHICO加盟店_検索結果_'+META.updated+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
async function init(){try{META=JSON.parse($('storeData').textContent);stores=META.stores;stores.forEach(s=>s.checked=META.updated);stores.forEach(s=>{s.town=townOf(s.address);s.searchText=norm(s.name+' '+s.address+' '+s.category+' '+s.type);});towns=[...new Set(stores.map(s=>s.town))].sort((a,b)=>a.localeCompare(b,'ja'));for(const town of towns){const o=document.createElement('option');o.value=o.textContent=town;$('town').append(o);}for(const type of [...new Set(stores.map(s=>s.type))].sort((a,b)=>a.localeCompare(b,'ja'))){const o=document.createElement('option');o.value=o.textContent=type;$('type').append(o);}render();
 if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'search_ichico_shops',description:'Search the official-data snapshot by keywords, normal rate and payment support and show matching shops. Returns the first 30 results and total count.',inputSchema:{type:'object',properties:{query:{type:'string'},normalRate:{type:'number',enum:[1,5]},cash:{type:'boolean'},card:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['query','normalRate','cash','card'].includes(k))||('query'in input&&typeof input.query!=='string')||('normalRate'in input&&![1,5].includes(input.normalRate))||['cash','card'].some(k=>k in input&&typeof input[k]!=='boolean'))throw Error('Invalid search conditions');clearFiltersForm();$('query').value=input.query||'';rate=input.normalRate?String(input.normalRate):'';$('cash').checked=!!input.cash;$('card').checked=!!input.card;render();return {count:matches.length,checked:META.checked,shops:matches.slice(0,30).map(({searchText,...s})=>s)};}});}catch(e){console.warn('Optional browser tool unavailable',e);}}
 }catch(e){$('summary').textContent='データを読み込めませんでした。ページを再読み込みしてください。';$('results').innerHTML='<div class="empty">通信環境を確認して再読み込みしてください。<br><a href="https://www.city.ichikawa.lg.jp/ichico-store/">公式検索を開く</a></div>';$('download').disabled=true;}}
init();

